// Copyright (c) 2004-2022 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MESA-2026.09

== MESA-2026.09

|===
|Version:          |MESA-2026.09
|Previous Version: |MESA-2026.06
|Date:             |2026-09-30
|Description:      |Roadmap release
|===

=== VCL actions and lookup flexibility

For SparX-5 and LAN969x families, the actions, lookup and key generation for VCL has been extended:

* VCL port key generation per lookup added in the `mesa_vcl_port_conf_t::lookup` field.
* VCE lookup parameter (0-3) added in the `mesa_vce_key_t::lookup` field.
** Lookup 0 and 1 map to VCAP CLM-A.
** Lookup 2 and 3 map to VCAP CLM-B.
* VCE generic key matching added in the `mesa_vce_key_t::gkey` field.
* VCE port filtering added in the `mesa_vce_action_t::port_action` and `mesa_vce_action_t::port_list` fields.
* VCE CPU copy options added in the added in the `mesa_vce_action_t::cpu` and `mesa_vce_action_t::cpu_queue` fields.
* VCE generic key control added in the `mesa_vce_action_t::gkey_mode` and `mesa_vce_action_t::gkey` fields.
** The generic key fields can be used to link rules in different lookups.

=== ACL lookup flexibility

For SparX-5 and LAN969x families, the lookup and key generation for ACL has been extended:

* ACL port key generation per lookup added in the `mesa_acl_port_conf_t::lookup` field.
* ACE lookup parameter (0-3) added in the `mesa_ace_t::lookup` field.
** Lookup 0 and 1 map to VCAP IS2-A.
** Lookup 2 and 3 map to VCAP IS2-B.
* ACL rules and port key generation can be configured in any order.

=== VCL key encoding selection

For devices with a non-zero `MESA_CAP_L2_VCL_KEY_SEL` capability, that is all devices
supporting VCL except the SparX-III/Caracal family, the key encoding can be selected per rule:

* `mesa_vce_key_t::key_enable` enables the encoding selection for the rule.
* `mesa_vce_key_t::key_type` and `mesa_vce_key_t::dmac_dip` determine the encoding.

By default, `key_enable` is disabled and the encoding of a rule is based on the key
generation of the first ingress port of the rule, as in previous releases.

The VCL port configuration (`mesa_vcl_port_conf_set()`) no longer fails if the port is
used as ingress port in existing VCL or VLAN translation rules. This applies to all
devices supporting VCL.

It is now up to the application to ensure that the port key generation matches the key
encoding of the rules using the port, and the two can be configured in any order.
