// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

#ifndef MEPA_VSC8574_PRIVATE_H
#define MEPA_VSC8574_PRIVATE_H

#include <stdint.h>
#include <microchip/ethernet/phy/api/types.h>
#include <microchip/ethernet/phy/api/phy_ts.h>

#define TRUE  1
#define FALSE 0

// Tesla family
#define VTSS_PHY_TESLA_REV_A 0
#define VTSS_PHY_TESLA_REV_B 1
#define VTSS_PHY_TESLA_REV_D 2
#define VTSS_PHY_TESLA_REV_E 3

#define VTSS_PHY_PAGE_STANDARD   0x0000 ///< Standard registers
#define VTSS_PHY_PAGE_EXTENDED   0x0001 ///< Extended registers
#define VTSS_PHY_PAGE_EXTENDED_2 0x0002 ///< Extended registers - page 2
#define VTSS_PHY_PAGE_EXTENDED_3 0x0003 ///< Extended registers - page 3
#define VTSS_PHY_PAGE_EXTENDED_4 0x0004 ///< Extended registers - page 4
#define VTSS_PHY_PAGE_GPIO       0x0010 ///< GPIO registers
#define VTSS_PHY_PAGE_1588       0x1588 ///< 1588 (PTP) registers
#define VTSS_PHY_PAGE_MACSEC     0x0004 ///< MACSEC page
#define VTSS_PHY_PAGE_TEST       0x2A30 ///< Test registers
#define VTSS_PHY_PAGE_TR         0x52B5 ///< Token ring registers
#define VTSS_PHY_PAGE_0x2DAF     0x2DAF ///< 0x2DAF registers
// PHY register page access for a single register can be done
// using an OR operation of the register address and the page below
#define VTSS_PHY_REG_STANDARD (VTSS_PHY_PAGE_STANDARD<<5) ///< Standard registers
#define VTSS_PHY_REG_EXTENDED (VTSS_PHY_PAGE_EXTENDED<<5) ///< Extended registers
#define VTSS_PHY_REG_GPIO     (VTSS_PHY_PAGE_GPIO<<5)     ///< GPIO registers
#define VTSS_PHY_REG_TEST     (VTSS_PHY_PAGE_TEST<<5)     ///< Test registers
#define VTSS_PHY_REG_TR       (VTSS_PHY_PAGE_TR<<5)       ///< Token ring registers

// Function for setting a bit in a vector. The cast keeps the essential type of
// the shift wide enough for the 16-bit PHY registers these masks address, so
// that shifting into the upper bits does not exceed the width of the left
// operand (MISRA C-2023 Rule 12.2).
#define VTSS_PHY_BIT(bit)       ((u16)1U << (bit))

// Set x bits to 1. E.g x=3 -> b111 (0x7). The shift is done on a 32-bit operand
// so that wide masks do not shift beyond the width of the left operand
// (MISRA C-2023 Rule 12.2). The result is deliberately left uncast: casting a
// constant composite up to u16 would violate Rule 10.8.
#define VTSS_PHY_BITMASK(x)               (((u32)1U << (x)) - 1U)

#define VTSS_PHY_EXTRACT_BITFIELD(value, offset, width)  (((value) >> (offset)) & VTSS_PHY_BITMASK(width))
#define VTSS_PHY_ENCODE_BITFIELD(value, offset, width)   (((u16)(value) & VTSS_PHY_BITMASK(width)) << (offset))
// Expressed as the difference of two bit masks rather than a shifted mask: it
// yields the same value without shifting a narrow constant (Rule 12.2) and
// without casting a composite expression to a wider type (Rule 10.8).
#define VTSS_PHY_ENCODE_BITMASK(offset, width)      (VTSS_PHY_BITMASK((offset) + (width)) - VTSS_PHY_BITMASK(offset))

// ** Register definitions - Standard page **

// Register 0 + Bit fields
#define  VTSS_PHY_MODE_CONTROL VTSS_PHY_PAGE_STANDARD, 0
#define  VTSS_F_PHY_MODE_CONTROL_SW_RESET         VTSS_PHY_BIT(15)
#define  VTSS_F_PHY_MODE_CONTROL_LOOP             VTSS_PHY_BIT(14)
#define  VTSS_F_PHY_MODE_CONTROL_AUTO_NEG_ENA     VTSS_PHY_BIT(12)
#define  VTSS_F_PHY_MODE_CONTROL_POWER_DOWN       VTSS_PHY_BIT(11)
#define  VTSS_F_PHY_MODE_CONTROL_ISOLATE          VTSS_PHY_BIT(10)
#define  VTSS_F_PHY_MODE_CONTROL_RESTART_AUTO_NEG VTSS_PHY_BIT(9)
#define  VTSS_F_PHY_MODE_CONTROL_UNIDIRECTIONAL   VTSS_PHY_BIT(5)


// Register 1 + Bit fields
#define  VTSS_PHY_MODE_STATUS VTSS_PHY_PAGE_STANDARD, 1
#define  VTSS_F_PHY_UNIDIRECTIONAL_ABILITY        VTSS_PHY_BIT(7)
#define  VTSS_F_PHY_STATUS_LINK_STATUS            VTSS_PHY_BIT(2)

// Register 2 + Bit fields
#define  VTSS_PHY_IDENTIFIER_1 VTSS_PHY_PAGE_STANDARD, 2

// Register 3 + Bit fields
#define  VTSS_PHY_IDENTIFIER_2 VTSS_PHY_PAGE_STANDARD, 3


// Register 4 + Bit fields
#define  VTSS_PHY_DEVICE_AUTONEG_ADVERTISEMENT VTSS_PHY_PAGE_STANDARD, 4
#define VTSS_PHY_DEVICE_AUTONEG_ADVERTISEMENT_100BASETX_FDX VTSS_PHY_BIT(8)
#define VTSS_PHY_DEVICE_AUTONEG_ADVERTISEMENT_100BASETX_HDX VTSS_PHY_BIT(7)
#define VTSS_PHY_DEVICE_AUTONEG_ADVERTISEMENT_10BASET_FDX   VTSS_PHY_BIT(6)
#define VTSS_PHY_DEVICE_AUTONEG_ADVERTISEMENT_10BASET_HDX   VTSS_PHY_BIT(5)

// Register 5 + Bit fields
#define  VTSS_PHY_AUTONEGOTIATION_LINK_PARTNER_ABILITY VTSS_PHY_PAGE_STANDARD, 5

// Register 6 + Bit fields
#define  VTSS_PHY_AUTONEGOTIATION_EXPANSION VTSS_PHY_PAGE_STANDARD, 6
#define  VTSS_PHY_AUTONEGOTIATION_EXPANSION_LOCAL_PHY_NXT_PG_CAPABLE   VTSS_PHY_BIT(2)
#define  VTSS_PHY_AUTONEGOTIATION_EXPANSION_PAGE_RECEIVED              VTSS_PHY_BIT(1)
#define  VTSS_PHY_AUTONEGOTIATION_EXPANSION_PAGE_LP_ANEG_CAPABLE       VTSS_PHY_BIT(0)

// Register 9 + Bit fields
#define VTSS_PHY_1000BASE_T_CONTROL  VTSS_PHY_PAGE_STANDARD, 9
#define VTSS_PHY_1000BASE_T_CONTROL_1000BASE_T_FDX_CAPABILITY VTSS_PHY_BIT(9)
#define VTSS_PHY_1000BASE_T_CONTROL_1000BASE_T_HDX_CAPABILITY VTSS_PHY_BIT(8)

//Register 10 + Bit fields
#define VTSS_PHY_1000BASE_T_STATUS VTSS_PHY_PAGE_STANDARD, 10

//Register 13 + Bit fields
#define VTSS_PHY_MMD_EEE_ACCESS VTSS_PHY_PAGE_STANDARD, 13

//Register 14 + Bit fields
#define VTSS_PHY_MMD_ADDR_OR_DATA VTSS_PHY_PAGE_STANDARD, 14

// Register 18 + Bit fields
#define VTSS_PHY_BYPASS_CONTROL VTSS_PHY_PAGE_STANDARD, 18
#define VTSS_F_PHY_BYPASS_CONTROL_HP_AUTO_MDIX_AT_FORCE VTSS_PHY_BIT(7)
#define VTSS_F_PHY_BYPASS_CONTROL_DISABLE_PARI_SWAP_CORRECTION VTSS_PHY_BIT(5)

// Register 19 + Bit fields
#define VTSS_PHY_ERROR_COUNTER_1 VTSS_PHY_PAGE_STANDARD, 19
#define VTSS_M_PHY_ERROR_COUNTER_1_100_1000BASETX_RX_ERR_CNT  VTSS_PHY_ENCODE_BITMASK(0, 7)

// Register 20 + Bit fields
#define VTSS_PHY_EXTENDED_CONTROL_AND_STATUS_20 VTSS_PHY_PAGE_STANDARD, 20
#define VTSS_M_PHY_ERROR_COUNTER_2_100_1000FALSE_CARRIER_ERR_CNT  VTSS_PHY_ENCODE_BITMASK(0, 7)

// Register 21 + Bit fields
#define VTSS_PHY_ERROR_COUNTER_3 VTSS_PHY_PAGE_STANDARD, 21
#define VTSS_M_PHY_ERROR_COUNTER_3_CU_MEDIA_LINK_DISCONN_ERR_CNT  VTSS_PHY_ENCODE_BITMASK(0, 7)

// Register 22 + Bit fields
#define VTSS_PHY_EXTENDED_CONTROL_AND_STATUS VTSS_PHY_PAGE_STANDARD, 22
#define VTSS_PHY_EXTENDED_CONTROL_AND_STATUS_FORCE_10BASE_T_HIGH VTSS_PHY_BIT(15)

// Register 23 + Bit fields
#define  VTSS_PHY_EXTENDED_PHY_CONTROL VTSS_PHY_PAGE_STANDARD, 23
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_RXCLK_BUG_15388        VTSS_PHY_BIT(13)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_MAC_INTERFACE_MODE     VTSS_PHY_BIT(12)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_MEDIA_OPERATING_MODE(value) VTSS_PHY_ENCODE_BITFIELD(value, 8, 3)
#define  VTSS_M_PHY_EXTENDED_PHY_CONTROL_MEDIA_OPERATING_MODE   VTSS_PHY_ENCODE_BITMASK(8,3)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_AMS_PREFERENCE         VTSS_PHY_BIT(11)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_AMS_ENABLED            VTSS_PHY_BIT(10)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_AMS_OVERRIDE(value)    VTSS_PHY_ENCODE_BITFIELD(value, 6, 2)
#define  VTSS_M_PHY_EXTENDED_PHY_CONTROL_AMS_OVERRIDE           VTSS_PHY_ENCODE_BITMASK(6,2)
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_FAR_END_LOOPBACK_MODE  VTSS_PHY_BIT(3)

// Register 24 + Bit fields
#define  VTSS_PHY_EXTENDED_PHY_CONTROL_2 VTSS_PHY_PAGE_STANDARD, 24
#define  VTSS_F_PHY_EXTENDED_PHY_CONTROL_2_CONNECTOR_LOOPBACK_MODE  VTSS_PHY_BIT(0)


// Register 25 + Bit fields
#define VTSS_PHY_INTERRUPT_MASK    VTSS_PHY_PAGE_STANDARD, 25

#define VTSS_F_PHY_INTERRUPT_MASK_INT_MASK                     VTSS_PHY_BIT(15)
#define VTSS_F_PHY_INTERRUPT_MASK_SPEED_STATE_CHANGE_MASK      VTSS_PHY_BIT(14)
#define VTSS_F_PHY_INTERRUPT_MASK_LINK_MASK                    VTSS_PHY_BIT(13)
#define VTSS_F_PHY_INTERRUPT_MASK_FDX_STATE_CHANGE_MASK        VTSS_PHY_BIT(12)
#define VTSS_F_PHY_INTERRUPT_MASK_AUTO_NEG_ERROR_MASK          VTSS_PHY_BIT(11)
#define VTSS_F_PHY_INTERRUPT_MASK_AUTO_NEG_COMPLETE_MASK       VTSS_PHY_BIT(10)
#define VTSS_F_PHY_INTERRUPT_MASK_INLINE_POW_DEV_DETECT_MASK   VTSS_PHY_BIT(9)
#define VTSS_F_PHY_INTERRUPT_MASK_SYMBOL_ERR_INT_MASK          VTSS_PHY_BIT(8)
#define VTSS_F_PHY_INTERRUPT_MASK_FAST_LINK_MASK               VTSS_PHY_BIT(7)
#define VTSS_F_PHY_INTERRUPT_MASK_WAKE_ON_LAN_MASK             VTSS_PHY_BIT(6)
#define VTSS_F_PHY_INTERRUPT_MASK_TX_FIFO_OVERFLOW_INT_MASK    VTSS_PHY_BIT(6)
#define VTSS_F_PHY_INTERRUPT_MASK_RX_FIFO_OVERFLOW_INT_MASK    VTSS_PHY_BIT(5)
#define VTSS_F_PHY_INTERRUPT_MASK_EXTENDED_INT_MASK            VTSS_PHY_BIT(5)
#define VTSS_F_PHY_INTERRUPT_MASK_AMS_MEDIA_CHANGE_MASK        VTSS_PHY_BIT(4)
#define VTSS_F_PHY_INTERRUPT_MASK_FALSE_CARRIER_INT_MASK       VTSS_PHY_BIT(3)
#define VTSS_F_PHY_INTERRUPT_MASK_LINK_SPEED_DS_DETECT_MASK    VTSS_PHY_BIT(2)
#define VTSS_F_PHY_INTERRUPT_MASK_MASTER_SLAVE_RES_ERR_MASK    VTSS_PHY_BIT(1)
#define VTSS_F_PHY_INTERRUPT_MASK_RX_ER_INT_MASK               VTSS_PHY_BIT(0)

// Register 26 + Bit fields
#define VTSS_PHY_INTERRUPT_STATUS   VTSS_PHY_PAGE_STANDARD, 26

// Register 27 + Bit fields
#define VTSS_PHY_STD_27 VTSS_PHY_PAGE_STANDARD, 27
#define VTSS_PHY_COBRA_LED_MODE_SELECT VTSS_PHY_PAGE_STANDARD, 27

// Register 28 + Bit fields
#define COOPER_VTSS_PHY_AUXILIARY_CONTROL_AND_STATUS   VTSS_PHY_PAGE_STANDARD, 23
#define VTSS_PHY_AUXILIARY_CONTROL_AND_STATUS   VTSS_PHY_PAGE_STANDARD, 28
#define VTSS_F_PHY_AUXILIARY_CONTROL_AND_STATUS_ANEG_COMPLETE                     VTSS_PHY_BIT(15)
#define VTSS_F_PHY_AUXILIARY_CONTROL_AND_STATUS_ANEG_DISABLED                     VTSS_PHY_BIT(14)
#define VTSS_F_PHY_AUXILIARY_CONTROL_AND_STATUS_HP_AUTO_MDIX_CROSSOVER_INDICATION VTSS_PHY_BIT(13)
#define VTSS_F_PHY_AUXILIARY_CONTROL_AND_STATUS_ACTIPHY_MODE_ENABLE               VTSS_PHY_BIT(6)

// Register 29 + Bit fields
#define VTSS_PHY_LED_MODE_SELECT VTSS_PHY_PAGE_STANDARD, 29


// Register 30 + Bit fields
#define VTSS_PHY_LED_BEHAVIOR  VTSS_PHY_PAGE_STANDARD, 30
#define VTSS_F_PHY_LED_BEHAVIOR_LED_PULSING_ENABLE     VTSS_PHY_BIT(12)

//Register 31
#define VTSS_PHY_PAGE    VTSS_PHY_PAGE_STANDARD, 31

// ** Register definitions -  EXT1 page**

// Register 17E1 + Bit fields
#define VTSS_PHY_REG_17E VTSS_PHY_PAGE_EXTENDED, 17

// Register 18E1 + Bit fields
#define VTSS_PHY_CU_MEDIA_CRC_GOOD_COUNTER VTSS_PHY_PAGE_EXTENDED, 18
#define VTSS_F_PHY_CU_MEDIA_CRC_GOOD_COUNTER_PACKET_SINCE_LAST_READ  VTSS_PHY_ENCODE_BITMASK(15, 1)
#define VTSS_M_PHY_CU_MEDIA_CRC_GOOD_COUNTER_CONTENTS  VTSS_PHY_ENCODE_BITMASK(0, 14)

// Register 19E1 + Bit fields
#define VTSS_PHY_EXTENDED_MODE_CONTROL VTSS_PHY_PAGE_EXTENDED, 19
#define VTSS_M_PHY_EXTENDED_MODE_CONTROL_FORCE_MDI_CROSSOVER  VTSS_PHY_ENCODE_BITMASK(2, 2)
#define VTSS_F_PHY_EXTENDED_MODE_CONTROL_FAST_LINK_FAILURE    VTSS_PHY_BIT(4)
#define VTSS_S_PHY_EXTENDED_MODE_CONTROL_FAST_LINK_FAILURE    4
#define VTSS_S_PHY_EXTENDED_MODE_CONTROL_SIGDET_POLARITY      0

// Register 20E1 + Bit fields
#define VTSS_PHY_EXTENDED_PHY_CONTROL_3 VTSS_PHY_PAGE_EXTENDED, 20
#define  VTSS_M_PHY_EXTENDED_PHY_CONTROL_3_MEDIA_MODE_STATUS  VTSS_PHY_ENCODE_BITMASK(6,2)

// Register 21E1 + Bit fields
#define VTSS_PHY_RESERVED_1_WS VTSS_PHY_PAGE_EXTENDED, 21

// Register 22E1 + Bit fields
#define VTSS_PHY_RESERVED_2_WS VTSS_PHY_PAGE_EXTENDED, 22



// Register 23E1 + Bit fields
#define VTSS_PHY_EXTENDED_PHY_CONTROL_4 VTSS_PHY_PAGE_EXTENDED, 23
#define VTSS_M_VTSS_PHY_EXTENDED_PHY_CONTROL_4_PHY_ADDRESS  VTSS_PHY_ENCODE_BITMASK(11, 5)
#define VTSS_M_VTSS_PHY_EXTENDED_PHY_CONTROL_4_CU_MEDIA_CRC_ERROR_COUNTER  VTSS_PHY_ENCODE_BITMASK(0, 7)


// Register 24E1 + Bit fields
#define VTSS_PHY_VERIPHY_CTRL_REG1 VTSS_PHY_PAGE_EXTENDED, 24
#define VTSS_F_PHY_VERIPHY_CTRL_REG1_TRIGGER VTSS_PHY_BIT(15)
#define VTSS_F_PHY_VERIPHY_CTRL_REG1_VALID   VTSS_PHY_BIT(14)
#define VTSS_M_PHY_VERIPHY_CTRL_REG1_PAIR_A_DISTANCE VTSS_PHY_ENCODE_BITMASK(8, 6)
#define VTSS_M_PHY_VERIPHY_CTRL_REG1_PAIR_B_DISTANCE VTSS_PHY_ENCODE_BITMASK(0, 6)

// Register 25E1 + Bit fields
#define VTSS_PHY_VERIPHY_CTRL_REG2 VTSS_PHY_PAGE_EXTENDED, 25
#define VTSS_M_PHY_VERIPHY_CTRL_REG2_PAIR_C_DISTANCE VTSS_PHY_ENCODE_BITMASK(8, 6)
#define VTSS_M_PHY_VERIPHY_CTRL_REG2_PAIR_D_DISTANCE VTSS_PHY_ENCODE_BITMASK(0, 6)

// Register 26E1 + Bit fields
#define VTSS_PHY_VERIPHY_CTRL_REG3 VTSS_PHY_PAGE_EXTENDED, 26
#define VTSS_M_PHY_VERIPHY_CTRL_REG3_PAIR_A_TERMINATION_STATUS VTSS_PHY_ENCODE_BITMASK(12, 4)
#define VTSS_M_PHY_VERIPHY_CTRL_REG3_PAIR_B_TERMINATION_STATUS VTSS_PHY_ENCODE_BITMASK(8, 4)
#define VTSS_M_PHY_VERIPHY_CTRL_REG3_PAIR_C_TERMINATION_STATUS VTSS_PHY_ENCODE_BITMASK(4, 4)
#define VTSS_M_PHY_VERIPHY_CTRL_REG3_PAIR_D_TERMINATION_STATUS VTSS_PHY_ENCODE_BITMASK(0, 4)


// Register 28E1 + Bit fields
#define VTSS_PHY_EXT_28 VTSS_PHY_PAGE_EXTENDED, 28
// Register 28E1 + Bit field overrides for Viper Rev. B enhanced EPG
#define VTSS_F_PHY_EXT_28_PKT_SZ_OV_ENA          VTSS_PHY_BIT(7)
#define VTSS_F_PHY_EXT_28_IPG_OV_ENA             VTSS_PHY_BIT(6)
#define VTSS_F_PHY_EXT_28_SIG_CTR_ENA            VTSS_PHY_BIT(5)
#define VTSS_F_PHY_EXT_28_ETYPE_UDPDEST_OV_ENA   VTSS_PHY_BIT(4)
#define VTSS_F_PHY_EXT_28_EPG_DATA_REG_IDX(val)  VTSS_PHY_ENCODE_BITFIELD(val, 0, 4)
#define VTSS_M_PHY_EXT_28_EPG_DATA_REG_IDX       VTSS_PHY_ENCODE_BITMASK(0, 4)

// Register 29E1 + Bit fields
#define EPG_CTRL_REG_1 VTSS_PHY_PAGE_EXTENDED, 29
#define VTSS_F_EPG_CTRL_REG_1_EPG_ENABLE              VTSS_PHY_BIT(15)
#define VTSS_F_EPG_CTRL_REG_1_EPG_RUN_STOP            VTSS_PHY_BIT(14)
#define VTSS_F_EPG_CTRL_REG_1_EPG_RUN_CONTINUOUS      VTSS_PHY_BIT(13)   // Viper B Enhanced EPG
#define VTSS_F_EPG_CTRL_REG_1_PKT_LENGTH(val)         VTSS_PHY_ENCODE_BITFIELD(val, 11, 2)
#define VTSS_F_EPG_CTRL_REG_1_IPG_8192NSEC            VTSS_PHY_BIT(10)
#define VTSS_F_EPG_CTRL_REG_1_MAC_DA_LOW_NIBBLE(val)  VTSS_PHY_ENCODE_BITFIELD(val, 6, 4)
#define VTSS_F_EPG_CTRL_REG_1_MAC_SA_LOW_NIBBLE(val)  VTSS_PHY_ENCODE_BITFIELD(val, 2, 4)
#define VTSS_F_EPG_CTRL_REG_1_RANDOM_PAYLOAD_PATTERN  VTSS_PHY_BIT(1)
#define VTSS_F_EPG_CTRL_REG_1_BAD_FRAME_FCS_GEN       VTSS_PHY_BIT(0)

#define VTSS_EPG_CTRL_REG_1_PKT_LEN_125               (0)
#define VTSS_EPG_CTRL_REG_1_PKT_LEN_64                (1)
#define VTSS_EPG_CTRL_REG_1_PKT_LEN_1518              (2)
#define VTSS_EPG_CTRL_REG_1_PKT_LEN_10000             (3)

// Register 30E1 + Bit fields
#define EPG_CTRL_REG_2 VTSS_PHY_PAGE_EXTENDED, 30



// ** Register definitions -  EXT2 page**
//Register 16E2
#define VTSS_PHY_CU_PMD_TX_CTRL VTSS_PHY_PAGE_EXTENDED_2, 16

//Register 17E2
#define VTSS_PHY_EEE_CONTROL VTSS_PHY_PAGE_EXTENDED_2, 17
#define VTSS_F_PHY_EEE_CONTROL_ENABLE_10BASE_TE VTSS_PHY_BIT(15)
#define VTSS_F_PHY_EEE_CONTROL_ENABLE_1000BASE_T_FORCE_MODE VTSS_PHY_BIT(5)

//Register 18E2
#define VTSS_EXTENDED_CHIP_ID          VTSS_PHY_PAGE_EXTENDED_2, 18

// Note: the RGMII skew control aliases of register 18E2, and register 20E2
// (VTSS_PHY_RGMII_CONTROL), are not defined here - this PHY does not support the
// RGMII MAC interface.

//Register 21E2
#define VTSS_PHY_WOL_LOWER_MAC_ADDR VTSS_PHY_PAGE_EXTENDED_2, 21

//Register 22E2
#define VTSS_PHY_WOL_MID_MAC_ADDR VTSS_PHY_PAGE_EXTENDED_2, 22

//Register 23E2
#define VTSS_PHY_WOL_UPPER_MAC_ADDR VTSS_PHY_PAGE_EXTENDED_2, 23

//Register 24E2
#define VTSS_PHY_WOL_LOWER_PASSWD VTSS_PHY_PAGE_EXTENDED_2, 24

//Register 25E2
#define VTSS_PHY_WOL_MID_PASSWD VTSS_PHY_PAGE_EXTENDED_2, 25

//Register 26E2
#define VTSS_PHY_WOL_UPPER_PASSWD VTSS_PHY_PAGE_EXTENDED_2, 26

//Register 27E2
#define VTSS_PHY_WOL_CONTROL VTSS_PHY_PAGE_EXTENDED_2, 27

#define VTSS_PHY_WOL_CONTROL_SECURE_ON_ENABLE         VTSS_PHY_BIT(15)
#define VTSS_PHY_WOL_CONTROL_SECURE_ON_PASSWD_LEN_4   VTSS_PHY_BIT(14)
#define VTSS_PHY_WOL_CONTROL_RESERVED_001             VTSS_PHY_BIT(13)
#define VTSS_PHY_WOL_CONTROL_RESERVED_002             VTSS_PHY_BIT(12)
#define VTSS_M_PHY_WOL_CONTROL_ADDR_REP_COUNT         VTSS_PHY_ENCODE_BITMASK(8, 4)
#define VTSS_M_PHY_WOL_CONTROL_RESERVED_003           VTSS_PHY_ENCODE_BITMASK(2, 6)
#define VTSS_PHY_WOL_CONTROL_MDINT_SIGNAL_SEP         VTSS_PHY_BIT(1)
#define VTSS_PHY_WOL_CONTROL_MDINT_CMOS_DRIVE_EN      VTSS_PHY_BIT(0)

//Register 28E2
#define VTSS_PHY_EXTENDED_INTERRUPT_MASK              VTSS_PHY_PAGE_EXTENDED_2, 28

#define VTSS_F_PHY_EXT_INT_MASK_RX_FIFO_UNDER_OVERFLOW_INT_MASK  VTSS_PHY_BIT(13)
#define VTSS_F_PHY_EXT_INT_MASK_TX_FIFO_UNDER_OVERFLOW_INT_MASK  VTSS_PHY_BIT(12)
#define VTSS_F_PHY_EXT_INT_MASK_RESERVED_001                     VTSS_PHY_BIT(11)
#define VTSS_F_PHY_EXT_INT_MASK_MEM_INTEGRITY_RING_CTL_INT_MASK  VTSS_PHY_BIT(10)
#define VTSS_F_PHY_EXT_INT_MASK_MACSEC_EGRESS_INT_MASK           VTSS_PHY_BIT(9)
#define VTSS_F_PHY_EXT_INT_MASK_MACSEC_INGRESS_INT_MASK          VTSS_PHY_BIT(8)
#define VTSS_F_PHY_EXT_INT_MASK_MACSEC_FLOW_CTL_INT_MASK         VTSS_PHY_BIT(7)
#define VTSS_F_PHY_EXT_INT_MASK_MACSEC_LINE_MAC_INT_MASK         VTSS_PHY_BIT(6)
#define VTSS_F_PHY_EXT_INT_MASK_MACSEC_HOST_MAC_INT_MASK         VTSS_PHY_BIT(5)
#define VTSS_F_PHY_EXT_INT_MASK_RR_SW_OVER_COMPL_INT_MASK        VTSS_PHY_BIT(4)
#define VTSS_F_PHY_EXT_INT_MASK_EEE_LINK_FAIL_INT_MASK           VTSS_PHY_BIT(3)
#define VTSS_F_PHY_EXT_INT_MASK_EEE_RX_TQ_TIMER_INT_MASK         VTSS_PHY_BIT(2)
#define VTSS_F_PHY_EXT_INT_MASK_EEE_RX_TS_TIMER_INT_MASK         VTSS_PHY_BIT(1)
#define VTSS_F_PHY_EXT_INT_MASK_EEE_WAKE_ERR_INT_MASK            VTSS_PHY_BIT(0)

//Register 29E2
#define VTSS_PHY_EXTENDED_INTERRUPT_STATUS            VTSS_PHY_PAGE_EXTENDED_2, 29

//Register 30E2
#define VTSS_PHY_EXTENDED_RING_RESILIENCY_CTRL        VTSS_PHY_PAGE_EXTENDED_2, 30

#define VTSS_F_PHY_EXT_RING_RSLNT_STARTUP_EN                     VTSS_PHY_BIT(15)
#define VTSS_F_PHY_EXT_RING_RSLNT_ADVERTISE_RING_RESILIENCY      VTSS_PHY_BIT(14)
#define VTSS_F_PHY_EXT_RING_RSLNT_LP_RING_RESILIENCY_ADVERTISE   VTSS_PHY_BIT(13)
#define VTSS_F_PHY_EXT_RING_RSLNT_FORCE_RING_RESILIENCY_EN       VTSS_PHY_BIT(12)
#define VTSS_F_PHY_EXT_RING_RSLNT_RING_RESILIENCY_STATUS         VTSS_PHY_ENCODE_BITMASK(4, 2)
#define VTSS_F_PHY_EXT_RING_RSLNT_START_SWITCHOVER               VTSS_PHY_BIT(0)

// ** Register definitions -  EXT3 page**
// Register 16E3
#define VTSS_PHY_MAC_SERDES_PCS_CONTROL VTSS_PHY_PAGE_EXTENDED_3, 16
#define VTSS_F_MAC_SERDES_PCS_CONTROL_MAC_IF_PD_ENA               VTSS_PHY_BIT(13)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_FORCE_ADV_ABILITY           VTSS_PHY_BIT(11)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_SGMII_OUTPUT_PREAMBLE       VTSS_PHY_BIT(8)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_ANEG_ENA                    VTSS_PHY_BIT(7)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_INV_POLARITY_AT_INPUT       VTSS_PHY_BIT(6)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_INV_POLARITY_AT_OUTPUT      VTSS_PHY_BIT(5)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_FAST_LINK_STATUS_ENA        VTSS_PHY_BIT(4)
#define VTSS_F_MAC_SERDES_PCS_CONTROL_INHIBIT_MAC_ODD_START_DELAY VTSS_PHY_BIT(2)

// Register 17E3
#define VTSS_PHY_MAC_SERDES_PCS_STATUS  VTSS_PHY_PAGE_EXTENDED_3, 17
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_SYNC_FAIL                VTSS_PHY_BIT(15)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_CGBAD                    VTSS_PHY_BIT(14)
#define VTSS_F_MAC_SERDES_PCS_STATUS_SGMII_ALIGN_ERROR            VTSS_PHY_BIT(12)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_LP_ANEG_RESTART          VTSS_PHY_BIT(11)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_FDX_ADV                  VTSS_PHY_BIT(5)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_HDX_ADV                  VTSS_PHY_BIT(4)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_LP_ANEG_CAPABLE          VTSS_PHY_BIT(3)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_LINK_STATUS              VTSS_PHY_BIT(2)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_ANEG_COMPLETE            VTSS_PHY_BIT(1)
#define VTSS_F_MAC_SERDES_PCS_STATUS_MAC_PCS_SIG_DETECT           VTSS_PHY_BIT(0)


// Register 18E3
#define VTSS_PHY_REVERED_18 VTSS_PHY_PAGE_EXTENDED_3, 18
#define VTSS_PHY_MAC_SERDES_CLAUSE_37_ADVERTISED_ABILITY VTSS_PHY_PAGE_EXTENDED_3, 18
#define VTSS_M_PHY_MAC_SERDES_CLAUSE_37_ADVERTISED_ABILITY  VTSS_PHY_ENCODE_BITMASK(0, 15)

// Register 20E3
#define VTSS_PHY_MAC_SERDES_STATUS VTSS_PHY_PAGE_EXTENDED_3, 20

// Register 21E3
#define VTSS_PHY_MEDIA_SERDES_TX_GOOD_PACKET_COUNTER  VTSS_PHY_PAGE_EXTENDED_3, 21
#define VTSS_F_PHY_MEDIA_SERDES_TX_GOOD_PACKET_COUNTER_ACTIVE VTSS_PHY_BIT(15)
#define VTSS_M_PHY_MEDIA_SERDES_TX_GOOD_PACKET_COUNTER_CNT    VTSS_PHY_ENCODE_BITMASK(0, 13)

// Register 22E3
#define VTSS_PHY_MEDIA_SERDES_TX_CRC_ERROR_COUNTER  VTSS_PHY_PAGE_EXTENDED_3, 22
#define VTSS_M_PHY_MEDIA_SERDES_TX_CRC_ERROR_COUNTER_TX_SELECT          VTSS_PHY_ENCODE_BITMASK(14, 2)
#define VTSS_F_PHY_MEDIA_SERDES_TX_CRC_ERROR_COUNTER_TX_SELECT(value)   VTSS_PHY_ENCODE_BITFIELD(value, 14, 2)
#define VTSS_F_PHY_MEDIA_SERDES_TX_CRC_ERROR_COUNTER_TX_PREAMBLE_FIX    VTSS_PHY_BIT(13)
#define VTSS_M_PHY_MEDIA_SERDES_TX_CRC_ERROR_COUNTER_CNT                VTSS_PHY_ENCODE_BITMASK(0, 7)

// Register 23E3
#define VTSS_PHY_MEDIA_SERDES_PCS_CONTROL    VTSS_PHY_PAGE_EXTENDED_3, 23
#define VTSS_M_PHY_MEDIA_SERDES_PCS_CNTL_REMOTE_FAULT_TO_MEDIA             VTSS_PHY_ENCODE_BITMASK(15, 14)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_MEDIA_IF_ANEG_PARALLEL_DETECT     VTSS_PHY_BIT(13)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_FORCE_ADVERTISED_ABILITY          VTSS_PHY_BIT(11)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_POLARITY_REVERSAL_INPUT           VTSS_PHY_BIT(6)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_POLARITY_REVERSAL_OUTPUT          VTSS_PHY_BIT(5)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_INHIBIT_ODD_START_DELAY           VTSS_PHY_BIT(4)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_100BASEFX_FORCE_HLS               VTSS_PHY_BIT(2)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_100BASEFX_FORCE_FEFI              VTSS_PHY_BIT(1)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_CNTL_100BASEFX_FEFI_FORCE_VALUE        VTSS_PHY_BIT(0)

// Register 24E3
#define VTSS_PHY_MEDIA_SERDES_PCS_STATUS     VTSS_PHY_PAGE_EXTENDED_3, 24
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_100BASEFX_PROTO_XFER_LINK_STATUS VTSS_PHY_BIT(13)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_10MB_LINK_STATUS                 VTSS_PHY_BIT(12)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_LP_FULL_DUPLEX                   VTSS_PHY_BIT(5)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_LP_HALF_DUPLEX                   VTSS_PHY_BIT(4)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_LP_ANEG_CAP                      VTSS_PHY_BIT(3)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_MEDIA_LINK_STATUS                VTSS_PHY_BIT(2)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_MEDIA_ANEG_COMPLETE              VTSS_PHY_BIT(1)
#define VTSS_F_PHY_MEDIA_SERDES_PCS_STATUS_MEDIA_SIG_DET                    VTSS_PHY_BIT(0)

// Register 25E3
#define VTSS_PHY_MEDIA_SERDES_CL37_ADV_ABILITY VTSS_PHY_PAGE_EXTENDED_3, 25

// Register 26E3
#define VTSS_PHY_MEDIA_SERDES_CLAUSE_37_LP_ABILITY VTSS_PHY_PAGE_EXTENDED_3, 26

// Register 27E3
#define VTSS_PHY_MEDIA_SERDES_STATUS                    VTSS_PHY_PAGE_EXTENDED_3, 27
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_COMMA_REALIGN                 VTSS_PHY_BIT(15)
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_SIG_DETECT                    VTSS_PHY_BIT(14)
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_100FX_FEFI_DETECT             VTSS_PHY_BIT(13)
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_COMMA_DETECT                  VTSS_PHY_BIT(12)
#define VTSS_M_PHY_MEDIA_SERDES_STATUS_COMMA_POSITION   VTSS_PHY_ENCODE_BITMASK(8, 11)
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_100FX_HLS_DETECT              VTSS_PHY_BIT(7)
#define VTSS_F_PHY_MEDIA_SERDES_STATUS_FIBER_SERDES_FREQ             VTSS_PHY_BIT(6)

// Register 28E3
#define VTSS_PHY_MEDIA_MAC_SERDES_RX_GOOD_COUNTER  VTSS_PHY_PAGE_EXTENDED_3, 28
#define VTSS_M_PHY_MEDIA_MAC_SERDES_RX_GOOD_COUNTER_CNT    VTSS_PHY_ENCODE_BITMASK(0, 13)

// Register 29E3
#define VTSS_PHY_MEDIA_MAC_SERDES_RX_CRC_CRC_ERR_COUNTER  VTSS_PHY_PAGE_EXTENDED_3, 29
#define VTSS_F_PHY_MEDIA_MAC_SERDES_RX_CRC_ERR_COUNTER_PKT_SINCE_LAST_RD  VTSS_PHY_BIT(15)
#define VTSS_M_PHY_MEDIA_MAC_SERDES_RX_CRC_ERR_COUNTER_RX_SELECT          VTSS_PHY_ENCODE_BITMASK(14, 2)
#define VTSS_F_PHY_MEDIA_MAC_SERDES_RX_CRC_ERR_COUNTER_RX_SELECT(value)   VTSS_PHY_ENCODE_BITFIELD(value, 14, 2)
#define VTSS_M_PHY_MEDIA_MAC_SERDES_RX_CRC_ERR_COUNTER_CNT                VTSS_PHY_ENCODE_BITMASK(0, 7)

// Register 26E4
#define VTSS_PHY_SPI_DAISY_CHAIN_CTRL                       VTSS_PHY_PAGE_EXTENDED_4, 26
#define VTSS_F_PHY_SPI_DAISY_CHAIN_CTRL_ENABLE_INPUT_PORT   VTSS_PHY_BIT(15)
#define VTSS_F_PHY_SPI_DAISY_CHAIN_CTRL_ENABLE_OUTPUT_PORT  VTSS_PHY_BIT(14)

// Register 28E4
#define VTSS_PHY_SPI_DAISY_CHAIN_CNTR                         VTSS_PHY_PAGE_EXTENDED_4, 28
#define VTSS_M_PHY_SPI_DAISY_CHAIN_CNTR_SELECT_DAISY_CHAIN_CNTR VTSS_PHY_ENCODE_BITMASK(15, 14)
#define VTSS_PHY_1588_PPS_0_MUX_CTRL                        VTSS_PHY_PAGE_EXTENDED_4, 21
#define VTSS_F_PHY_1588_PPS_0_MUX_CTRL_1588_SOFT_RESET      VTSS_PHY_BIT(15)

// ** Register definitions -  GPIO page**
#define VTSS_PHY_GPIO_0 VTSS_PHY_PAGE_GPIO, 0
#define VTSS_PHY_GPIO_3 VTSS_PHY_PAGE_GPIO, 3
#define VTSS_PHY_GPIO_4 VTSS_PHY_PAGE_GPIO, 4
#define VTSS_PHY_GPIO_5 VTSS_PHY_PAGE_GPIO, 5
#define VTSS_PHY_GPIO_6 VTSS_PHY_PAGE_GPIO, 6
#define VTSS_PHY_GPIO_7 VTSS_PHY_PAGE_GPIO, 7
#define VTSS_PHY_GPIO_8 VTSS_PHY_PAGE_GPIO, 8
#define VTSS_PHY_GPIO_9 VTSS_PHY_PAGE_GPIO, 9
#define VTSS_PHY_GPIO_10 VTSS_PHY_PAGE_GPIO, 10
#define VTSS_PHY_GPIO_11 VTSS_PHY_PAGE_GPIO, 11
#define VTSS_PHY_GPIO_12 VTSS_PHY_PAGE_GPIO, 12
#define VTSS_PHY_GPIO_15 VTSS_PHY_PAGE_GPIO, 15

// Register 13G + Bit fields
#define VTSS_PHY_SIGDET_GPIO_CONTROL VTSS_PHY_PAGE_GPIO, 13
#define VTSS_M_PHY_SIGDET_GPIO_CONTROL_GPIO0        VTSS_PHY_ENCODE_BITMASK(0, 2)
#define VTSS_F_PHY_SIGDET_GPIO_CONTROL_GPIO0(value) VTSS_PHY_ENCODE_BITFIELD(value, 0, 2)
#define VTSS_M_PHY_SIGDET_GPIO_CONTROL_GPIO1 VTSS_PHY_ENCODE_BITMASK(2, 2)
#define VTSS_F_PHY_SIGDET_GPIO_CONTROL_GPIO1(value) VTSS_PHY_ENCODE_BITFIELD(value, 2, 2)
#define VTSS_M_PHY_SIGDET_GPIO_CONTROL_GPIO2 VTSS_PHY_ENCODE_BITMASK(8, 2)
#define VTSS_F_PHY_SIGDET_GPIO_CONTROL_GPIO2(value) VTSS_PHY_ENCODE_BITFIELD(value, 2, 2)
#define VTSS_M_PHY_SIGDET_GPIO_CONTROL_GPIO3 VTSS_PHY_ENCODE_BITMASK(10, 2)
#define VTSS_F_PHY_SIGDET_GPIO_CONTROL_GPIO3(value) VTSS_PHY_ENCODE_BITFIELD(value, 10, 2)

// Register 14G + Bit fields
#define VTSS_PHY_GPIO_CONTROL_2 VTSS_PHY_PAGE_GPIO, 14
#define VTSS_M_PHY_GPIO_CONTROL_2_GPIO12_GPIO13            VTSS_PHY_ENCODE_BITMASK(14, 2)
#define VTSS_F_PHY_GPIO_CONTROL_2_COMA_MODE_OUTPUT_ENABLE  VTSS_PHY_BIT(13)
#define VTSS_F_PHY_GPIO_CONTROL_2_COMA_MODE_OUTPUT_DATA    VTSS_PHY_BIT(12)
#define VTSS_M_PHY_GPIO_CONTROL_2_GPIO4                    VTSS_PHY_ENCODE_BITMASK(0, 2)
#define VTSS_F_PHY_GPIO_CONTROL_2_GPIO4(value)             VTSS_PHY_ENCODE_BITFIELD(value, 0, 2)
#define VTSS_M_PHY_GPIO_CONTROL_2_GPIO5                    VTSS_PHY_ENCODE_BITMASK(2, 2)
#define VTSS_F_PHY_GPIO_CONTROL_2_GPIO5(value)             VTSS_PHY_ENCODE_BITFIELD(value, 2, 2)

// Register 15G
#define VTSS_PHY_GPIO_INPUT VTSS_PHY_PAGE_GPIO, 15

// Register 16G
#define VTSS_PHY_GPIO_OUTPUT VTSS_PHY_PAGE_GPIO, 16

// Register 17G
#define VTSS_PHY_GPIO_IN_OUT_CONF VTSS_PHY_PAGE_GPIO, 17
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO0    VTSS_PHY_BIT(0)
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO1    VTSS_PHY_BIT(1)
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO2    VTSS_PHY_BIT(4)
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO3    VTSS_PHY_BIT(5)
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO4    VTSS_PHY_BIT(8)
#define VTSS_F_PHY_GPIO_IN_OUT_CONF_GPIO5    VTSS_PHY_BIT(9)

// Register 18G
#define VTSS_PHY_MICRO_PAGE VTSS_PHY_PAGE_GPIO, 18

// Register 19G + Bit fields
#define      VTSS_PHY_GPIO_CONTROL_3 VTSS_PHY_PAGE_GPIO, 19
#define      VTSS_PHY_MAC_MODE_AND_FAST_LINK VTSS_PHY_PAGE_GPIO, 19
#define VTSS_F_PHY_MAC_MODE_AND_FAST_LINK_MAC_IF_MODE_SELECT(value)  VTSS_PHY_ENCODE_BITFIELD(value, 14, 2)
#define VTSS_M_MAC_MODE_AND_FAST_LINK_MAC_IF_MODE_SELECT VTSS_PHY_ENCODE_BITMASK(14, 2)
#define VTSS_M_PHY_GPIO_CONTROL_3_MAC_IF_MODE_SELECT VTSS_PHY_ENCODE_BITMASK(14, 2)

// Register 20G + Bit fields
#define VTSS_PHY_I2C_MUX_CONTROL_1 VTSS_PHY_PAGE_GPIO, 20
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_DEV_ADDR(value)  VTSS_PHY_ENCODE_BITFIELD(value, 9, 7)
#define VTSS_M_PHY_I2C_MUX_CONTROL_1_DEV_ADDR         VTSS_PHY_ENCODE_BITMASK(9, 7)
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_SCL_CLK_FREQ(value)  VTSS_PHY_ENCODE_BITFIELD(value, 4, 2)
#define VTSS_M_PHY_I2C_MUX_CONTROL_1_SCL_CLK_FREQ         VTSS_PHY_ENCODE_BITMASK(4, 2)
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_PORT_3_ENABLE        VTSS_PHY_BIT(3)
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_PORT_2_ENABLE        VTSS_PHY_BIT(2)
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_PORT_1_ENABLE        VTSS_PHY_BIT(1)
#define VTSS_F_PHY_I2C_MUX_CONTROL_1_PORT_0_ENABLE        VTSS_PHY_BIT(0)

// Register 21G + Bit fields
#define VTSS_PHY_I2C_MUX_CONTROL_2 VTSS_PHY_PAGE_GPIO, 21
#define VTSS_F_PHY_I2C_MUX_CONTROL_2_MUX_READY            VTSS_PHY_BIT(15)
#define VTSS_F_PHY_I2C_MUX_CONTROL_2_PHY_PORT_ADDR(value) VTSS_PHY_ENCODE_BITFIELD(value, 10, 2)
#define VTSS_M_PHY_I2C_MUX_CONTROL_2_PHY_PORT_ADDR        VTSS_PHY_ENCODE_BITMASK(10, 1)
#define VTSS_F_PHY_I2C_MUX_CONTROL_2_ENA_I2C_MUX_ACCESS   VTSS_PHY_BIT(9)
#define VTSS_F_PHY_I2C_MUX_CONTROL_2_RD                   VTSS_PHY_BIT(8)
#define VTSS_F_PHY_I2C_MUX_CONTROL_2_ADDR(value)          VTSS_PHY_ENCODE_BITFIELD(value, 0, 8)
#define VTSS_M_PHY_I2C_MUX_CONTROL_2_ADDR                 VTSS_PHY_ENCODE_BITMASK(7, 0)

// Register 22G + Bit fields
#define VTSS_PHY_I2C_MUX_DATA_READ_WRITE VTSS_PHY_PAGE_GPIO, 22
#define VTSS_M_PHY_I2C_MUX_DATA_READ_WRITE_READ_DATA          VTSS_PHY_ENCODE_BITMASK(8, 8)
#define VTSS_F_PHY_I2C_MUX_DATA_READ_WRITE_WRITE_DATA(value)  VTSS_PHY_ENCODE_BITFIELD(value, 0, 8)
#define VTSS_M_PHY_I2C_MUX_DATA_READ_WRITE_WRITE_DATA         VTSS_PHY_ENCODE_BITMASK(0, 8)

// Register 23G + Bit fields
#define VTSS_PHY_RECOVERED_CLOCK_0_CONTROL VTSS_PHY_PAGE_GPIO, 23

// Register 24G + Bit fields
#define VTSS_PHY_RECOVERED_CLOCK_1_CONTROL VTSS_PHY_PAGE_GPIO, 24


// Register 25G + Bit fields
#define VTSS_PHY_ENHANCED_LED_CONTROL VTSS_PHY_PAGE_GPIO, 25

// Register 26G + Bit fields
#define VTSS_PHY_TEMP_CONF VTSS_PHY_PAGE_GPIO, 26

// Register 28G + Bit fields
#define VTSS_PHY_TEMP_VAL VTSS_PHY_PAGE_GPIO, 28

// Register 30G + Bit fields
#define VTSS_PHY_EXTENDED_REVISION             VTSS_PHY_PAGE_GPIO, 30
#define VTSS_F_PHY_EXTENDED_REVISION_TESLA_E   VTSS_PHY_BIT(0)


// ** Register definitions -  TEST page**
#define VTSS_PHY_TEST_PAGE_0 VTSS_PHY_PAGE_TEST, 0
#define VTSS_PHY_TEST_PAGE_1 VTSS_PHY_PAGE_TEST, 1
#define VTSS_PHY_TEST_PAGE_2 VTSS_PHY_PAGE_TEST, 2
#define VTSS_PHY_TEST_PAGE_3 VTSS_PHY_PAGE_TEST, 3
#define VTSS_PHY_TEST_PAGE_5 VTSS_PHY_PAGE_TEST, 5
#define VTSS_PHY_TEST_PAGE_8 VTSS_PHY_PAGE_TEST, 8
#define VTSS_PHY_TEST_PAGE_9 VTSS_PHY_PAGE_TEST, 9
#define VTSS_PHY_TEST_PAGE_12 VTSS_PHY_PAGE_TEST, 12
#define VTSS_PHY_TEST_PAGE_19 VTSS_PHY_PAGE_TEST, 19
#define VTSS_PHY_TEST_PAGE_20 VTSS_PHY_PAGE_TEST, 20
#define VTSS_PHY_TEST_PAGE_22 VTSS_PHY_PAGE_TEST, 22
#define VTSS_PHY_TEST_PAGE_23 VTSS_PHY_PAGE_TEST, 23
#define VTSS_PHY_TEST_PAGE_24 VTSS_PHY_PAGE_TEST, 24
#define VTSS_PHY_TEST_PAGE_25 VTSS_PHY_PAGE_TEST, 25
#define VTSS_PHY_TEST_PAGE_27 VTSS_PHY_PAGE_TEST, 27
#define VTSS_PHY_TEST_PAGE_28 VTSS_PHY_PAGE_TEST, 28


// ** Register definitions -  TR page**
#define VTSS_PHY_PAGE_TR_0 VTSS_PHY_PAGE_TR, 0
#define VTSS_PHY_PAGE_TR_1 VTSS_PHY_PAGE_TR, 1
#define VTSS_PHY_PAGE_TR_2 VTSS_PHY_PAGE_TR, 2
#define VTSS_PHY_PAGE_TR_16 VTSS_PHY_PAGE_TR, 16
#define VTSS_PHY_PAGE_TR_17 VTSS_PHY_PAGE_TR, 17
#define VTSS_PHY_PAGE_TR_18 VTSS_PHY_PAGE_TR, 18

// ** Register definitions -  1588 page**
#define VTSS_PHY_PAGE_1588_16 VTSS_PHY_PAGE_1588, 16
#define VTSS_PHY_F_PAGE_1588_16_CMD_BIT  VTSS_PHY_BIT(15)
#define VTSS_PHY_F_PAGE_1588_16_READ  VTSS_PHY_BIT(14)
#define VTSS_PHY_F_PAGE_1588_16_TARGET(value) VTSS_PHY_ENCODE_BITFIELD(value, 11, 3)
#define VTSS_PHY_F_PAGE_1588_16_CSR_REG_ADDR(value) VTSS_PHY_ENCODE_BITFIELD(value, 0, 11)

#define VTSS_PHY_PAGE_1588_CSR_DATA_LSB VTSS_PHY_PAGE_1588, 17
#define VTSS_PHY_PAGE_1588_CSR_DATA_MSB VTSS_PHY_PAGE_1588, 18


// ** Register definitions -  MACSEC page**
#define VTSS_PHY_PAGE_MACSEC_19 VTSS_PHY_PAGE_MACSEC, 19
#define VTSS_PHY_PAGE_MACSEC_20 VTSS_PHY_PAGE_MACSEC, 20
#define VTSS_PHY_F_PAGE_MACSEC_19_CMD_BIT  VTSS_PHY_BIT(15)
#define VTSS_PHY_F_PAGE_MACSEC_20_READY(value) VTSS_PHY_ENCODE_BITFIELD(value, 13, 2)

#define VTSS_PHY_F_PAGE_MACSEC_19_READ  VTSS_PHY_BIT(14)
#define VTSS_PHY_F_PAGE_MACSEC_19_TARGET(value) VTSS_PHY_ENCODE_BITFIELD(value, 12, 2)
#define VTSS_PHY_F_PAGE_MACSEC_20_TARGET(value) VTSS_PHY_ENCODE_BITFIELD(value, 0, 4)
#define VTSS_PHY_F_PAGE_MACSEC_19_CSR_REG_ADDR(value) VTSS_PHY_ENCODE_BITFIELD(value, 0, 14)

#define VTSS_PHY_PAGE_MACSEC_CSR_DATA_LSB VTSS_PHY_PAGE_MACSEC, 17
#define VTSS_PHY_PAGE_MACSEC_CSR_DATA_MSB VTSS_PHY_PAGE_MACSEC, 18


// Done with registers

#define VTSS_PHY_ACTIPHY_PWR        100 ///< ActiPHY power status
#define VTSS_PHY_LINK_DOWN_PWR      200U ///< Link down power status
#define VTSS_PHY_LINK_UP_FULL_PWR   400U ///< Link up full power status

// structs and defines
typedef BOOL vsc8574_event_t;

/// \brief PHY 1G configuration
typedef struct {
    struct {
        BOOL cfg;                               ///< Manual Master/Slave Config. 1=enabled
        BOOL val;                               ///< Master/Slave Config value, 1=Master
    } master;                             ///< Master/Slave Mode
} vtss_phy_conf_1g_t;

/// \brief PHY media interface type
typedef enum {
    VTSS_PHY_MEDIA_IF_CU,                      ///< Copper Interface
    VTSS_PHY_MEDIA_IF_SFP_PASSTHRU,            ///< Fiber/Cu SFP Pass-thru
    VTSS_PHY_MEDIA_IF_FI_1000BX,               ///< 1000Base-X
    VTSS_PHY_MEDIA_IF_FI_100FX,                ///< 100Base-FX
    VTSS_PHY_MEDIA_IF_AMS_CU_PASSTHRU,         ///< AMS - Cat5/SerDes/CuSFP passthru - Note the phy mode must be set to VTSS_PHY_MODE_ANEG
    VTSS_PHY_MEDIA_IF_AMS_FI_PASSTHRU,         ///< AMS - Fiber passthru - Note the phy mode must be set to VTSS_PHY_MODE_ANEG
    VTSS_PHY_MEDIA_IF_AMS_CU_1000BX,           ///< AMS - Cat5/1000BX/CuSFP
    VTSS_PHY_MEDIA_IF_AMS_FI_1000BX,
    VTSS_PHY_MEDIA_IF_AMS_CU_100FX,            ///< AMS - Cat5/100FX/CuSFP
    VTSS_PHY_MEDIA_IF_AMS_FI_100FX
} vtss_phy_media_interface_t;

/// \brief PHY media interface type
typedef enum {
    VTSS_PHY_MDIX_AUTO,                ///< Copper media MDI auto detected
    VTSS_PHY_MDI,                      ///< Copper media forced to MDI
    VTSS_PHY_MDIX,                     ///< Copper media forced to MDI-X (Crossed cable)
} vtss_phy_mdi_t;

/// \brief Port speed
typedef enum
{
    VTSS_SPEED_UNDEFINED,   ///< Undefined
    VTSS_SPEED_10M,         ///< 10 M
    VTSS_SPEED_100M,        ///< 100 M
    VTSS_SPEED_1G,          ///< 1 G
    VTSS_SPEED_2500M,       ///< 2.5G
    VTSS_SPEED_5G,          ///< 5G or 2x2.5G
    VTSS_SPEED_10G,         ///< 10 G
    VTSS_SPEED_12G,         ///< 12G
    VTSS_SPEED_25G,         ///< 25G
    VTSS_SPEED_AUTO
} vsc8574_port_speed_t;

/// \brief PHY mode
typedef enum {
    VTSS_PHY_MODE_ANEG,       ///< Auto negoatiation
    VTSS_PHY_MODE_FORCED,     ///< Forced mode
    VTSS_PHY_MODE_POWER_DOWN  ///< Power down (disabled)
} vtss_phy_mode_t;

/// \brief PHY forced mode configuration
typedef struct {
    vsc8574_port_speed_t speed; ///< Speed
    BOOL              fdx;   ///< Full duplex
} vtss_phy_forced_t;

/// \brief PHY auto negotiation advertisement
typedef struct {
    BOOL speed_10m_hdx;    ///< 10Mbps, half duplex
    BOOL speed_10m_fdx;    ///< 10Mbps, full duplex
    BOOL speed_100m_hdx;   ///< 100Mbps, half duplex
    BOOL speed_100m_fdx;   ///< 100Mbps, full duplex
    BOOL speed_1g_fdx;     ///< 1000Mpbs, full duplex
    BOOL speed_1g_hdx;     ///< 1000Mpbs, full duplex
    BOOL symmetric_pause;  ///< Symmetric pause
    BOOL asymmetric_pause; ///< Asymmetric pause
    BOOL tx_remote_fault;  ///< Local Application fault indication for Link Partner
    BOOL speed_2g5_fdx;    ///< 2500Mpbs, full duplex
    BOOL speed_5g_fdx;     ///< 5GE, full duplex
    BOOL speed_10g_fdx;    ///< 10GE, full duplex
    BOOL no_restart_aneg;  ///< Do not restart aneg
} vtss_phy_aneg_t;

/// \brief PHY fast link failure pin enable/disable
typedef enum {
    VTSS_PHY_FAST_LINK_FAIL_ENABLE = 1,    ///< Enable fast link failure pin
    VTSS_PHY_FAST_LINK_FAIL_DISABLE,       ///< Disble fast link failure pin
} vtss_phy_fast_link_fail_t;

/// \brief PHY Sigdet pin polarity configuration
typedef enum {
     VTSS_PHY_SIGDET_POLARITY_ACT_LOW = 1,   ///< Set Sigdet polarity Active low
     VTSS_PHY_SIGDET_POLARITY_ACT_HIGH,      ///< Set Sigdet polarity Active High
} vtss_phy_sigdet_polarity_t;

/// \brief PHY Unidirectional enable/disable
typedef enum {
    VTSS_PHY_UNIDIRECTIONAL_DISABLE = 0,   ///< Disable Unidirectional (Default)
    VTSS_PHY_UNIDIRECTIONAL_ENABLE,        ///< Enable Unidirectional
} vtss_phy_unidirectional_t;

/// \brief PHY MEDIA SerDes PCS Remote Fault Indication, See Clause 37, Table 37-3
typedef enum {
    VTSS_PHY_MAC_SERD_PCS_SGMII_IN_PRE_NONE    = 0,    ///< MAC SerDes PCS Control, SGMII Input Preamble for 100BaseX - No Preamble Req'd
    VTSS_PHY_MAC_SERD_PCS_SGMII_IN_PRE_ONE     = 1,    ///< MAC SerDes PCS Control, SGMII Input Preamble for 100BaseX - One-Byte Preamble Req'd
    VTSS_PHY_MAC_SERD_PCS_SGMII_IN_PRE_TWO     = 2,    ///< MAC SerDes PCS Control, SGMII Input Preamble for 100BaseX - Two-Byte Preamble Req'd
    VTSS_PHY_MAC_SERD_PCS_SGMII_IN_PRE_RSVD    = 3     ///< MAC SerDes PCS Control, SGMII Input Preamble for 100BaseX - Reserved
} vtss_phy_mac_serd_pcs_sgmii_pre;

/// \brief PHY MAC SerDes PCS Control, Reg16E3
typedef struct {
    BOOL                             disable;            ///< MAC i/f disable: 1000BaseX MAC i/f disable when media link down
    BOOL                             restart;            ///< MAC i/f restart: 1000BaseX MAC i/f restart on media link change
    BOOL                             pd_enable;          ///< MAC i/f ANEG parallel detect enable
    BOOL                             aneg_restart;       ///< Restart MAC i/f ANEG
    BOOL                             force_adv_ability;  ///< Force adv. ability from Reg18E3
    vtss_phy_mac_serd_pcs_sgmii_pre  sgmii_in_pre;       ///< SGMII Input Preamble for 100BaseFX
    BOOL                             sgmii_out_pre;      ///< SGMII Output Preamble
    BOOL                             serdes_aneg_ena;    ///< MAC SerDes ANEG Enable
    BOOL                             serdes_pol_inv_in;  ///< Invert SerDes Polarity at input of MAC
    BOOL                             serdes_pol_inv_out; ///< Invert SerDes Polarity at output of MAC
    BOOL                             fast_link_stat_ena; ///< Fast Link Fail Status Enable
    BOOL                             inhibit_odd_start;  ///< Inhibit MAC Odd-Start delay
} vtss_phy_mac_serd_pcs_cntl_t;

/// \brief PHY MEDIA SerDes PCS Remote Fault Indication, See Clause 37, Table 37-3
typedef enum {
    VTSS_PHY_MEDIA_SERD_PCS_REM_FAULT_NO_ERROR   = 0,    ///< Media SerDes PCS Control, Most Recent Clause 37 ANEG Exchg - Table 37-3
    VTSS_PHY_MEDIA_SERD_PCS_REM_FAULT_OFFLINE    = 1,    ///< Media SerDes PCS Control, Most Recent Clause 37 ANEG Exchg
    VTSS_PHY_MEDIA_SERD_PCS_REM_FAULT_LINK_FAIL  = 2,    ///< Media SerDes PCS Control, Most Recent Clause 37 ANEG Exchg
    VTSS_PHY_MEDIA_SERD_PCS_REM_FAULT_ANEG_ERROR = 3     ///< Media SerDes PCS Control, Most Recent Clause 37 ANEG Exchg
} vtss_phy_media_rem_fault_t;

/// \brief PHY MEDIA SerDes PCS Control, Reg23E3
typedef struct {
    vtss_phy_media_rem_fault_t  remote_fault;    ///< Remote Fault to Media indication sent in most recent Clause 37 ANEG
    BOOL   aneg_pd_detect;                       ///< SerDes MEDIA ANEG parallel detect enable
    BOOL   force_adv_ability;                    ///< Force adv. ability from Reg25E3
    BOOL   serdes_pol_inv_in;                    ///< Invert SerDes Polarity at input of Media SerDes
    BOOL   serdes_pol_inv_out;                   ///< Invert SerDes Polarity at output of Media SerDes
    BOOL   inhibit_odd_start;                    ///< Inhibit Media Odd-Start delay
    BOOL   force_hls;                            ///< Forces 100BaseFX to Tx HSL continuously
    BOOL   force_fefi;                           ///< Forces 100BaseFX Far-End-Fault Indication
    BOOL   force_fefi_value;                     ///< Forces/Suppress FEFI
} vtss_phy_media_serd_pcs_cntl_t;

/// \brief PHY AMS Force configuration
typedef enum {
    VTSS_PHY_MEDIA_FORCE_AMS_SEL_NORMAL   = 0,    ///< Force AMS Override to Force Selection - Normal
    VTSS_PHY_MEDIA_FORCE_AMS_SEL_SERDES   = 1,    ///< Force AMS Override to Force Selection - SerDes Media
    VTSS_PHY_MEDIA_FORCE_AMS_SEL_COPPER   = 2     ///< Force AMS Override to Force Selection - Copper Media
} vtss_phy_media_force_ams_sel_t;


typedef struct
{
    BOOL obey_pause;               ///< This port should obey PAUSE frames
    BOOL generate_pause;           ///< Link partner obeys PAUSE frames
} vsc8574_aneg_t;                     ///< Auto negotiation result

// Power configuration
typedef struct {
    BOOL vtss_phy_power_dynamic;
    BOOL vtss_phy_actiphy_on;
    u32  pwrusage;
} vtss_phy_power_t;

/// \brief Port status parameter struct
typedef struct
{
    vsc8574_event_t      link_down;       ///< Link down event occurred since last call
    BOOL              link;            ///< Link is up. Remaining fields only valid if TRUE
    vsc8574_port_speed_t speed;           ///< Speed
    BOOL              fdx;             ///< Full duplex
    BOOL              remote_fault;    ///< Remote fault signalled
    BOOL              aneg_complete;   ///< Autoneg completed (for clause_37 and Cisco aneg)
    BOOL              unidirectional_ability; ///< TRUE: PHY able to transmit from media independent interface regardless of whether the PHY has
    ///< determined that a valid link has been established.FALSE: PHY able to transmit from media
    ///< independent interface only when the PHY has determined that a valid link has been established.
    ///< Note This bit is only applicable to 100BASE-FX and 1000BASE-X fiber media modes.
    vsc8574_aneg_t aneg;                  ///< Auto negotiation result
    BOOL mdi_cross;                    ///< Indication of if Auto-MDIX crossover is performed
    BOOL fiber;                        ///< Indication of if the link is a fiber link, TRUE if link is a fiber link. FALSE if link is cu link or No Media
    BOOL copper;                       ///< Indication of if the link is a copper link, TRUE if link is a copper link. FALSE if link is fiber link or No Media
} vsc8574_port_status_t;

typedef struct {
    vtss_phy_mode_t                 mode;         ///< PHY mode
    vtss_phy_forced_t               forced;       ///< Forced mode configuration
    vtss_phy_aneg_t                 aneg;         ///< Auto-negotiation mode configuration
    vtss_phy_mdi_t                  mdi;          ///< Cu cable MDI (Crossed cable / normal cable)
    vtss_phy_fast_link_fail_t       flf;          ///< Fast link failure configuration
    vtss_phy_sigdet_polarity_t      sigdet;       ///< Sigdet pin polarity configuration
    vtss_phy_unidirectional_t       unidir;       ///< Unidirectional Configuration
    vtss_phy_mac_serd_pcs_cntl_t    mac_if_pcs;   ///< PHY MAC SerDes PCS Control (Reg16E3)
    vtss_phy_media_serd_pcs_cntl_t  media_if_pcs; ///< PHY MAC SerDes PCS Control (Reg23E3)
    vtss_phy_media_force_ams_sel_t  force_ams_sel;///< PHY Media AMS Force Selection
} vtss_phy_conf_t;

// Max Offset Part of Work-Around for Long Linkup Time in Forced Mode
#define VTSS_FORCED_LONG_LINKUP_COUNTER_WINDOW   (3U)

// Start address of the 8051 micro patch in PRAM, from vtss_phy_init_scripts.h
#define FIRMWARE_START_ADDR 0x4000

// Forced reset selection. Mirrors mesa_phy_forced_reset_t, which in the full vtss
// driver lives in vtss_phy_reset_conf_t as the .force member.
typedef enum {
    VSC8574_FORCE_RESET = 0,   // Force reset of PHY, regardless of config and HW state
    VSC8574_NOFORCE_RESET = 1, // Only reset if SW and HW MAC/MEDIA config differ
} vsc8574_forced_reset_t;

typedef struct {
    mepa_port_no_t port_no;
    mepa_port_interface_t mac_if;
    vtss_phy_media_interface_t media_if;
    mepa_device_t *base_dev;
    u16 int_mask_reg;
    u16 ev_mask;
    BOOL link_down_due_to_port_reset;
    vtss_phy_conf_t conf;
    vtss_phy_conf_1g_t conf_1g;
    vsc8574_port_status_t status;
    u16 revision;
    vtss_phy_power_t power;
    vsc8574_forced_reset_t force;
    // Last MAC interface programmed for this port, see vsc8574_mac_if_changed()
    mepa_port_interface_t mac_if_old;
    // Remaining member of vtss_phy_reset_conf_t that the reset path needs. MEPA
    // does not carry it in mepa_reset_param_t, so it stays at its default unless
    // something sets it explicitly.
    mesa_phy_pkt_mode_t pkt_mode;
    // CRC read back from the 8051 micro patch, see vsc8574_phy_is_8051_crc_ok_private()
    u16 micro_patch_crc;
    // Set once SFP pass-through mode has been configured for this port, so that the
    // one-shot ANEG restart in vsc8574_phy_pass_through_speed_mode() only happens
    // on the first entry into pass-through. Cleared on a forced port reset.
    BOOL cu_sfp_config_complete;
} vsc8574_data_t;

#endif
